### ISSUE TITLE
Nog geen sockets?

### ISSUE THREAD

**Issue by KoopReynders** [CathelijneVisser/CTC-A-chatbot#18]
Ik zie geen socket in de dependencies?
Klopt dat? Of komt dat nog?

https://github.com/CathelijneVisser/CTC-A-chatbot/blob/5139c567dccd6013b14901f15f8acdbc124da9d1/package.json#L24

**Comment by CathelijneVisser** [comment]
Alle socket dingen staan niet in de main maar in de branch "chatbot"
