### ISSUE TITLE
Wat doet Meta http-equiv="X-UA-Compatible"?

### ISSUE THREAD

**Issue by KoopReynders** [CathelijneVisser/CTC-A-chatbot#19]
Way doe deze meta tag eigenlijk? 
En is het nodig?

https://github.com/CathelijneVisser/CTC-A-chatbot/blob/5139c567dccd6013b14901f15f8acdbc124da9d1/views/partials/head.ejs#L5

**Comment by CathelijneVisser** [comment]
Ik was hem vergeten weg te halen heb het gedaan.

**Comment by KoopReynders** [comment]
Weet je wat die doet?
