### ISSUE TITLE
Wiki schrijven

### ISSUE THREAD

**Issue by CathelijneVisser** [CathelijneVisser/CTC-A-chatbot#2]
- [x] Analyseren
- [x] Ontwerpen
- [x] Bouwen
- [x] Integreren
- [x] Testen

**Comment by CathelijneVisser** [comment]
- [ ] Analyseren
- [ ] Ontwerpen
- [ ] Bouwen
- [ ] Integreren
- [ ] Testen

**Comment by CelinexPutte** [comment]
Af op 01-06
