### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by KoopReynders** [CathelijneVisser/CTC-A-chatbot#20]
Je kan ook per pagina de title aanpassen, dat elke pagina een unieke titel krijgt. (en dat zie je dan in de browser)

https://github.com/CathelijneVisser/CTC-A-chatbot/blob/5139c567dccd6013b14901f15f8acdbc124da9d1/views/partials/head.ejs#L7

**Comment by CathelijneVisser** [comment]
Mag je een aparte head per pagina maken?

**Comment by KoopReynders** [comment]
Dat zou zonde zijn van de partials !
Misschien kun je data meegeven aan de partial include?

**Comment by CathelijneVisser** [comment]
gefixed
